---
title: "anova"
author: "amel de angeli"
date: "2025-03-19"
output: html_document
---

```{r setup, include=FALSE}
library(readxl)
mytilus = as.data.frame(read_excel("mytilus.xlsx"))
mytilus

colnames(mytilus)
table(mytilus$Location)
summary(mytilus$Aam)
summary(mytilus)

mytilus$Location=factor(mytilus$Location) #transformer la variable nominale en facteur

summary(mytilus)# nv résumé


```
### Résumé graphique

```{r}
boxplot(Aam ~Location, mytilus, main="taille par ville", col= 1:5+1)

plot(mytilus$Aam)
abline(h=mean(mytilus$Aam), col="orange", lty=2)

plot(mytilus$Location)
```
Résumé par groupe

```{r}
aggregate(Aam ~Location, mytilus, mean)
res=tapply(mytilus$Aam,mytilus$Location,median)
res+1
res['Newport']
```
ANOVA
```{r}
mod_aov=aov(Aam~Location, mytilus)
summary(mod_aov)

mod_lm=lm(Aam~Location, mytilus)
summary(mod_lm)
tapply(mytilus$Aam, mytilus$Location, mean)
  
```
```{r}
#test shapiro par groupe
tapply(mytilus$Aam, mytilus$Location,shapiro.test)
shapiro.test(residuals(mod_lm))

qqnorm(residuals(mod_lm))
qqline(residuals(mod_lm))
```
Homogeneité de variances
```{r}
car::leveneTest(mytilus$Aam, mytilus$Location)
car::leveneTest(mod_lm)


```

Test Post-Hoc
```{r}
TukeyHSD(mod_aov)
summary(mod_lm)
```
Non homogeneite des variances
```{r}
(red=oneway.test(Aam~Location , mytilus))
```

