---
title: "golub"
author: "amel de angeli"
date: "2025-03-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Load & QC
```{r}
dim(golub)
class(golub)
class(golub.cl)
length(golub.cl)

dim(golub.gnames)
class(golub.gnames)
head(golub.gnames)

row_m=rowMeans(golub)
plot(row_m)
hist(row_m, nclass = 30)



```
dispersion
```{r}
row_sd= apply(golub, 1, sd)
plot(row_sd)
hist(row_sd, ndclass=30)
row_sd_q=quantile(row_sd, probs = c(0.25,0.50,0.75))
abline(v=row_sd_q,col="red2", lwd=2)


res=t.test(golub.cl, golub[1,])
str(res)
res$p.value

score = function(i) {
    return(res$p.value)
  res=t.test(golub.cl,golub[i,])
  return(res$p.value)
}
score(1)

row_scores=NULL
for(i in 1:nrow(golub)){
  row_scores[i]=score(i)
}

score2 = function(i) {
  res=t.test(i~golub.cl)
  return(res$p.value)
}

row_scores=NULL
for(i in 1:nrow(golub)){
  row_scores[i]=score2(golub[i,])
}

score(1)
score(10)

row_scores[10]

score_row=apply(golub,1,score2)

quantile(golub[1,], probs = c(0.25, 0.75))


quartiles = function(x) {
  quantile(x, probs = c(0.25, 0.75))
}
quartiles(golub[1,])
qq_row=t(apply(golub,1,quartiles))

dim(qq_row)

#écriture simplifiée en passant les parametres directement par apply
qq_row=t(apply(golub,1,quantile,probs=c(0.25, 0.75)))

dim(qq_row)


```
```{r}
#p-value
score_row
hist(row_scores, breaks=20)
length(score_row)
```
## Simulations
###Simulation effet nul

La matrice de mesures contient des valeurs issues d'une loi normale

```{r}
set.seed(25)
simul0=matrix(rnorm(nrow(golub)*ncol(golub)),nrow = nrow(golub), ncol=ncol(golub))
simul0[1:5,1:3]
image(simul0)

install.packages("pheatmap")
library(pheatmap)
pheatmap(simul0)

score_simul0 = apply(simul0, 1, score2)

score_simul1=apply(simul0, 1,score2)
hist(score_simul1, breaks=20)


golub.cl
simul1=simul0
simul1[1:300,28:38]=1.5+ simul1[1:300,28:38]


pheatmap(simul1)
pheatmap(simul1, cluster_rows = FALSE, cluster_cols = FALSE)

score_simul1=apply(simul1, 1,score2)
hist(score_simul1, breaks = 20)

which(score_simul1<5/100)
table(score_simul1<5/100,1:length(score_simul1)<=300)

hist(score_simul1,breaks=20,col="#0088CC44")
hist(score_simul0,breaks=20,col="#8800CC44", add=TRUE)

#recuperation comptages
hh1=hist(score_simul1,breaks=20,plot=FALSE)

FP=mean(hh1$counts[5:20])#moyenne 
D=hh1$counts[1]
FDR= FP/D
cat(FDR)

hh1$breaks
```
# passage de 5 à 2%


```{r}
hh50=hist(score_simul1,breaks=100/2,plot=TRUE)

FP=mean(hh50$counts[hh50$mids>0.2])#moyenne 
D=hh50$counts[1]
D
FDR= FP/D
cat(FDR)
```
```{r}
#entrees: vecteur des p values, seuil des p-values, seuil des p values des faux positifs
#sorties= fdr, nb découvertes

calculFDR = function(score,pValues,pValuesFP) {
  vecteur=hist(score,breaks=100/pValues,plot=TRUE)
  FP=mean(vecteur$counts[vecteur$mids>pValuesFP]) 
  D=vecteur$counts[1]
  FDR= FP/D
  return(FDR) 
}

calculFDR(score_simul1,2,0.2)
calculFDR(score_simul1,5,0.2)
```

